#!/bin/bash
#SBATCH -J IC-workflow_dir
#SBATCH -p kshcnormal                # <<< 修改：你的队列
#SBATCH -N 2
#SBATCH --ntasks-per-node=16
#SBATCH -t 02:00:00              # <<< 修改：时长


module purge
module load python/3.8.10

# python new_miss_dir.py
python Auto_dir.py